jobs:
  extended:
    if: github.event_name == 'push'
    name: Extended build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
      with:
        allowed-endpoints: 'github.com:443 raw.githubusercontent.com:443 artifactcache.actions.githubusercontent.com:443
          blob.core.windows.net:443 repo.maven.apache.org:443 coveralls.io:443 javadoc.io:443
          docs.oracle.com:443 docs.gradle.org:443 plugins.gradle.org:443 services.gradle.org:443
          downloads.gradle-dn.com:443

          '
        disable-telemetry: true
        egress-policy: block
    - continue-on-error: true
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
    - continue-on-error: true
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2
      with:
        architecture: x64
        cache: maven
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Build project
      run: ./mvnw jacoco:prepare-agent verify jacoco:report coveralls:report -DrepoToken=${{
        secrets.coveralls }} -Pextras -Pchecks -Panalysis -Pintegration -Pchecksum-enforce
  hotspot-32:
    name: HotSpot (32 bit)
    needs:
    - extended
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
    - continue-on-error: true
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2
      with:
        architecture: x86
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build project
      run: ./mvnw verify -Pintegration -Pjava${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        os:
        - ubuntu-20.04
        - windows-2022
  hotspot-ea:
    continue-on-error: true
    name: HotSpot (EA)
    needs:
    - extended
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
    - continue-on-error: true
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2
      with:
        cache: maven
        distribution: temurin
        java-version: 23-ea
    - continue-on-error: true
      name: Build project
      run: ./mvnw verify -Pjava23
  hotspot-legacy:
    name: HotSpot (legacy)
    needs:
    - extended
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
    - continue-on-error: true
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
      with:
        key: ${{ runner.os }}-legacy-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-legacy-maven-
    - continue-on-error: true
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2
      with:
        architecture: x64
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build project
      run: ./mvnw -s .mvn/nossl.settings.xml verify -Pintegration -Pjava${{ matrix.java
        }}
    strategy:
      fail-fast: false
      matrix:
        java:
        - 6
        - 7
  hotspot-supported:
    name: Any (supported)
    needs:
    - extended
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
    - continue-on-error: true
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2
      with:
        architecture: x64
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build project
      run: ./mvnw verify -Pintegration -Pjava${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
        os:
        - ubuntu-20.04
        - macos-12
        - windows-2022
  hotspot-unsupported:
    name: HotSpot (unsupported)
    needs:
    - extended
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
    - continue-on-error: true
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2
      with:
        architecture: x64
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build project
      run: ./mvnw verify -Pintegration -Pjava${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        java:
        - 9
        - 10
        - 12
        - 13
        - 14
        - 15
        - 16
        - 18
        - 19
        - 20
        - 22
  j9-supported:
    name: Any (supported)
    needs:
    - extended
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
    - continue-on-error: true
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2
      with:
        architecture: x64
        cache: maven
        distribution: adopt-openj9
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build project
      run: ./mvnw verify -Pintegration -Pjava${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        os:
        - ubuntu-20.04
        - macos-12
        - windows-2022
  release:
    if: github.event_name == 'push' && startsWith(github.event.head_commit.message,
      '[release]')
    name: Release new version
    needs:
    - extended
    - hotspot-ea
    - hotspot-supported
    - j9-supported
    - hotspot-unsupported
    - hotspot-32
    - hotspot-legacy
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
      with:
        egress-policy: audit
    - continue-on-error: true
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
    - continue-on-error: true
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2
      with:
        architecture: x64
        distribution: temurin
        gpg-private-key: ${{ secrets.gpg_secret }}
        java-version: 8
    - continue-on-error: true
      name: Publish new version
      run: 'git config user.name "${{ github.event.head_commit.committer.name }}"

        git config user.email "${{ github.event.head_commit.committer.email }}"

        ./mvnw -B -s .mvn/release.settings.xml release:prepare release:perform -Drepository.url=https://${{
        github.actor }}:${{ secrets.github_token }}@github.com/${{ github.repository
        }}.git -Dcentral.username=raphw -Dcentral.password=${{ secrets.central_password
        }} -Dgpg.passphrase=${{ secrets.gpg_passphrase }} -Dgpg.keyname=B4AC8CDC141AF0AE468D16921DA784CCB5C46DD5
        -Dgradle.key=${{ secrets.gradle_key }} -Dgradle.secret=${{ secrets.gradle_secret
        }} -Pchecksum-enforce

        '
name: CI
on:
  repository_dispatch:
    types: trigger-ga___main.yml
permissions: read-all
