jobs:
  analysis:
    name: Scorecards analysis
    permissions:
      id-token: write
      security-events: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        persist-credentials: false
    - continue-on-error: true
      uses: ossf/scorecard-action@3e15ea8318eee9b333819ec77a36aca8d39df13e
      with:
        publish_results: true
        results_file: results.sarif
        results_format: sarif
    - continue-on-error: true
      uses: github/codeql-action/upload-sarif@3e7e3b32d0fb8283594bb0a76cc60a00918b0969
      with:
        sarif_file: results.sarif
name: Scorecards
on:
  repository_dispatch:
    types: trigger-ga___scorecards.yml
permissions: read-all
